title: Souvenirs of an Electric Co.
owner: Florent Dufour
email: florent@dufour.xyz
description: Florent Dufour's blog

baseurl: ""
url: "https://blog.dufour.xyz"
language: en
encoding: utf-8
timezone: Europe/Paris

github_username: f-dufour
instagram_username: flrnt.dfr

markdown: kramdown

permalink: /:categories/:title

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle

excerpt_separator: <!--more-->
